"""empty message

Revision ID: 106c1d7888a0
Revises: 22578d59da1c
Create Date: 2020-04-02 16:12:28.310735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '106c1d7888a0'
down_revision = '22578d59da1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.alter_column('ghost_user', 'first_name',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    op.alter_column('ghost_user', 'last_name',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    op.drop_index('ix_ghost_user_first_name', table_name='ghost_user')
    op.drop_index('ix_ghost_user_last_name', table_name='ghost_user')
    op.alter_column('offcampus', 'price',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('offcampus', 'street',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('offcampus', 'zipcode',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index('ix_offcampus_country', table_name='offcampus')
    op.drop_index('ix_offcampus_nBathroom', table_name='offcampus')
    op.drop_index('ix_offcampus_nKitchen', table_name='offcampus')
    op.drop_index('ix_offcampus_nParking', table_name='offcampus')
    op.drop_index('ix_offcampus_nRoom', table_name='offcampus')
    op.drop_index('ix_offcampus_size', table_name='offcampus')
    op.drop_index('ix_offcampus_zipcode', table_name='offcampus')
    op.drop_column('offcampus', 'country')
    op.drop_index('ix_oncampus_dorm_1', table_name='oncampus')
    op.drop_index('ix_oncampus_dorm_2', table_name='oncampus')
    op.drop_index('ix_oncampus_dorm_3', table_name='oncampus')
    op.drop_column('pets', 'description')
    op.add_column('posts', sa.Column('image_1', sa.LargeBinary(), nullable=True))
    op.add_column('posts', sa.Column('image_2', sa.LargeBinary(), nullable=True))
    op.add_column('posts', sa.Column('image_3', sa.LargeBinary(), nullable=True))
    op.drop_index('ix_user_bedtime', table_name='user')
    op.drop_index('ix_user_noise_Sen', table_name='user')
    op.drop_index('ix_user_partyFreq', table_name='user')
    op.drop_index('ix_user_visitorFreq', table_name='user')
    op.drop_index('ix_user_wakeup', table_name='user')
    op.drop_column('user', 'has_pet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_pet', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_index('ix_user_wakeup', 'user', ['wakeup'], unique=False)
    op.create_index('ix_user_visitorFreq', 'user', ['visitorFreq'], unique=False)
    op.create_index('ix_user_partyFreq', 'user', ['partyFreq'], unique=False)
    op.create_index('ix_user_noise_Sen', 'user', ['noise_Sen'], unique=False)
    op.create_index('ix_user_bedtime', 'user', ['bedtime'], unique=False)
    op.drop_column('posts', 'image_3')
    op.drop_column('posts', 'image_2')
    op.drop_column('posts', 'image_1')
    op.add_column('pets', sa.Column('description', mysql.VARCHAR(length=200), nullable=True))
    op.create_index('ix_oncampus_dorm_3', 'oncampus', ['dorm_3'], unique=False)
    op.create_index('ix_oncampus_dorm_2', 'oncampus', ['dorm_2'], unique=False)
    op.create_index('ix_oncampus_dorm_1', 'oncampus', ['dorm_1'], unique=False)
    op.add_column('offcampus', sa.Column('country', mysql.VARCHAR(length=60), nullable=False))
    op.create_index('ix_offcampus_zipcode', 'offcampus', ['zipcode'], unique=False)
    op.create_index('ix_offcampus_size', 'offcampus', ['size'], unique=False)
    op.create_index('ix_offcampus_nRoom', 'offcampus', ['nRoom'], unique=False)
    op.create_index('ix_offcampus_nParking', 'offcampus', ['nParking'], unique=False)
    op.create_index('ix_offcampus_nKitchen', 'offcampus', ['nKitchen'], unique=False)
    op.create_index('ix_offcampus_nBathroom', 'offcampus', ['nBathroom'], unique=False)
    op.create_index('ix_offcampus_country', 'offcampus', ['country'], unique=False)
    op.alter_column('offcampus', 'zipcode',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('offcampus', 'street',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('offcampus', 'price',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_index('ix_ghost_user_last_name', 'ghost_user', ['last_name'], unique=False)
    op.create_index('ix_ghost_user_first_name', 'ghost_user', ['first_name'], unique=False)
    op.alter_column('ghost_user', 'last_name',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.alter_column('ghost_user', 'first_name',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.create_table('images',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('images', sa.BLOB(), nullable=True),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='images_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
