"""empty message

Revision ID: 22578d59da1c
Revises: e15121d1c55c
Create Date: 2020-03-31 01:21:56.330470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22578d59da1c'
down_revision = 'e15121d1c55c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_ibfk_1', 'posts', type_='foreignkey')
    op.drop_column('posts', 'owner_id')
    op.add_column('user', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'post_id')
    op.add_column('posts', sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('posts_ibfk_1', 'posts', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
