"""empty message

Revision ID: e15121d1c55c
Revises: 
Create Date: 2020-03-31 00:56:31.835878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e15121d1c55c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('school', sa.Integer(), nullable=True),
    sa.Column('has_pet', sa.Boolean(), nullable=True),
    sa.Column('is_smoke', sa.Boolean(), nullable=True),
    sa.Column('has_car', sa.Boolean(), nullable=True),
    sa.Column('has_bike', sa.Boolean(), nullable=True),
    sa.Column('noise_Sen', sa.Integer(), nullable=True),
    sa.Column('wakeup', sa.Integer(), nullable=True),
    sa.Column('bedtime', sa.Integer(), nullable=True),
    sa.Column('partyFreq', sa.Integer(), nullable=True),
    sa.Column('visitorFreq', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bedtime'), 'user', ['bedtime'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_noise_Sen'), 'user', ['noise_Sen'], unique=False)
    op.create_index(op.f('ix_user_partyFreq'), 'user', ['partyFreq'], unique=False)
    op.create_index(op.f('ix_user_school'), 'user', ['school'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_index(op.f('ix_user_visitorFreq'), 'user', ['visitorFreq'], unique=False)
    op.create_index(op.f('ix_user_wakeup'), 'user', ['wakeup'], unique=False)
    op.create_table('allergies',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('name', 'user_id')
    )
    op.create_table('ghost_user',
    sa.Column('representer_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['representer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('representer_id', 'email')
    )
    op.create_index(op.f('ix_ghost_user_email'), 'ghost_user', ['email'], unique=True)
    op.create_index(op.f('ix_ghost_user_first_name'), 'ghost_user', ['first_name'], unique=False)
    op.create_index(op.f('ix_ghost_user_last_name'), 'ghost_user', ['last_name'], unique=False)
    op.create_table('pets',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('name', 'user_id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_type', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_post_type'), 'posts', ['post_type'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('images', sa.LargeBinary(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lives',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.create_table('offcampus',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('state', sa.String(length=60), nullable=False),
    sa.Column('country', sa.String(length=60), nullable=False),
    sa.Column('zipcode', sa.Integer(), nullable=False),
    sa.Column('nParking', sa.Integer(), nullable=True),
    sa.Column('nRoom', sa.Integer(), nullable=True),
    sa.Column('nBathroom', sa.Integer(), nullable=True),
    sa.Column('nKitchen', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('pet_allowed', sa.Boolean(), nullable=True),
    sa.Column('substance_free', sa.Boolean(), nullable=True),
    sa.Column('ac', sa.Boolean(), nullable=True),
    sa.Column('laundry', sa.Boolean(), nullable=True),
    sa.Column('dishwasher', sa.Boolean(), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_index(op.f('ix_offcampus_city'), 'offcampus', ['city'], unique=False)
    op.create_index(op.f('ix_offcampus_country'), 'offcampus', ['country'], unique=False)
    op.create_index(op.f('ix_offcampus_nBathroom'), 'offcampus', ['nBathroom'], unique=False)
    op.create_index(op.f('ix_offcampus_nKitchen'), 'offcampus', ['nKitchen'], unique=False)
    op.create_index(op.f('ix_offcampus_nParking'), 'offcampus', ['nParking'], unique=False)
    op.create_index(op.f('ix_offcampus_nRoom'), 'offcampus', ['nRoom'], unique=False)
    op.create_index(op.f('ix_offcampus_size'), 'offcampus', ['size'], unique=False)
    op.create_index(op.f('ix_offcampus_state'), 'offcampus', ['state'], unique=False)
    op.create_index(op.f('ix_offcampus_zipcode'), 'offcampus', ['zipcode'], unique=False)
    op.create_table('oncampus',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('college', sa.Integer(), nullable=False),
    sa.Column('dorm_1', sa.String(length=60), nullable=True),
    sa.Column('dorm_2', sa.String(length=60), nullable=True),
    sa.Column('dorm_3', sa.String(length=60), nullable=True),
    sa.Column('drawNo', sa.Integer(), nullable=True),
    sa.Column('nSingles', sa.Integer(), nullable=True),
    sa.Column('nDoubles', sa.Integer(), nullable=True),
    sa.Column('nTriples', sa.Integer(), nullable=True),
    sa.Column('nQuads', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_index(op.f('ix_oncampus_dorm_1'), 'oncampus', ['dorm_1'], unique=False)
    op.create_index(op.f('ix_oncampus_dorm_2'), 'oncampus', ['dorm_2'], unique=False)
    op.create_index(op.f('ix_oncampus_dorm_3'), 'oncampus', ['dorm_3'], unique=False)
    op.create_index(op.f('ix_oncampus_nDoubles'), 'oncampus', ['nDoubles'], unique=False)
    op.create_index(op.f('ix_oncampus_nQuads'), 'oncampus', ['nQuads'], unique=False)
    op.create_index(op.f('ix_oncampus_nSingles'), 'oncampus', ['nSingles'], unique=False)
    op.create_index(op.f('ix_oncampus_nTriples'), 'oncampus', ['nTriples'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oncampus_nTriples'), table_name='oncampus')
    op.drop_index(op.f('ix_oncampus_nSingles'), table_name='oncampus')
    op.drop_index(op.f('ix_oncampus_nQuads'), table_name='oncampus')
    op.drop_index(op.f('ix_oncampus_nDoubles'), table_name='oncampus')
    op.drop_index(op.f('ix_oncampus_dorm_3'), table_name='oncampus')
    op.drop_index(op.f('ix_oncampus_dorm_2'), table_name='oncampus')
    op.drop_index(op.f('ix_oncampus_dorm_1'), table_name='oncampus')
    op.drop_table('oncampus')
    op.drop_index(op.f('ix_offcampus_zipcode'), table_name='offcampus')
    op.drop_index(op.f('ix_offcampus_state'), table_name='offcampus')
    op.drop_index(op.f('ix_offcampus_size'), table_name='offcampus')
    op.drop_index(op.f('ix_offcampus_nRoom'), table_name='offcampus')
    op.drop_index(op.f('ix_offcampus_nParking'), table_name='offcampus')
    op.drop_index(op.f('ix_offcampus_nKitchen'), table_name='offcampus')
    op.drop_index(op.f('ix_offcampus_nBathroom'), table_name='offcampus')
    op.drop_index(op.f('ix_offcampus_country'), table_name='offcampus')
    op.drop_index(op.f('ix_offcampus_city'), table_name='offcampus')
    op.drop_table('offcampus')
    op.drop_table('lives')
    op.drop_table('images')
    op.drop_index(op.f('ix_posts_post_type'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('pets')
    op.drop_index(op.f('ix_ghost_user_last_name'), table_name='ghost_user')
    op.drop_index(op.f('ix_ghost_user_first_name'), table_name='ghost_user')
    op.drop_index(op.f('ix_ghost_user_email'), table_name='ghost_user')
    op.drop_table('ghost_user')
    op.drop_table('allergies')
    op.drop_index(op.f('ix_user_wakeup'), table_name='user')
    op.drop_index(op.f('ix_user_visitorFreq'), table_name='user')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_school'), table_name='user')
    op.drop_index(op.f('ix_user_partyFreq'), table_name='user')
    op.drop_index(op.f('ix_user_noise_Sen'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_bedtime'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
